import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import Preloader from "@/components/Preloader";
import { getServerContentLocale } from "@/lib/get-server-content-locale";
import {
  cmsHttpsUrl,
  DEFAULT_PRELOADER_COMPANY_NAME,
  pickPreloaderString,
} from "@/lib/preloader-settings";
import { getAllSettings } from "@/lib/settings";
import FloatingButton from "@/components/FloatingButton";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-plus-jakarta-sans",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const DEFAULT_SITE_TITLE = DEFAULT_PRELOADER_COMPANY_NAME;

export async function generateMetadata(): Promise<Metadata> {
  let settings: Record<string, unknown> = {};

  try {
    settings = await getAllSettings();
  } catch {
    settings = {};
  }

  const locale = await getServerContentLocale();
  const siteTitle = pickPreloaderString(
    settings,
    "company_name",
    DEFAULT_SITE_TITLE,
    locale,
  );
  const faviconUrl =
    cmsHttpsUrl(settings.favicon) ?? cmsHttpsUrl(settings.company_logo);

  const metadata: Metadata = {
    title: {
      default: siteTitle,
      template: `%s | ${siteTitle}`,
    },
    description: "Generated by create next app",
  };

  if (faviconUrl) {
    metadata.icons = { icon: faviconUrl, shortcut: faviconUrl };
  }

  return metadata;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let preloaderSettings: Record<string, unknown> | undefined;
  try {
    preloaderSettings = await getAllSettings();
  } catch {
    preloaderSettings = undefined;
  }

  return (
    <html
      lang="en"
      className={`${plusJakartaSans.variable} ${inter.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="flex min-h-svh flex-col overflow-x-hidden font-sans antialiased">
        <Preloader settings={preloaderSettings} />
        <LanguageProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <FloatingButton />
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
